app/urls.py
from django.urls import path

from . import views

app_name='app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('wyniki/', views.Wyniki, name='Wyniki'),
]

projekt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Uzytkownik(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    wiek = models.CharField(max_length=50)
    plec = models.CharField(max_length=20, default="0")
    miasto = models.CharField(max_length=100)
    wyksztalcenie = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)


class Czestosc(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    okazja = models.CharField(max_length=200)
    czestotliwosc = models.CharField(max_length=200)
    pierwszy_kontakt = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

class Alkohol(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    rodzaj_alkoholu = models.CharField(max_length=200)
    piwo = models.CharField(max_length=100)
    wodka = models.CharField(max_length=100)
    wino = models.CharField(max_length=100)
    inne = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import  Question, Choice, Uzytkownik, Alkohol, Czestosc


class IndexView(generic.ListView):
    template_name = 'app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'app/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'app/results.html'

def Wyniki(request):
    return render(request, 'app/wyniki.html', {})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        if question_id<5:
            selected_choice = question.uzytkownik_set.get(pk=request.POST['uzytkownik'])
        if question_id>4 and question_id<8:
            selected_choice = question.czestosc_set.get(pk=request.POST['czestosc'])
        if question_id>7:
            selected_choice = question.alkohol_set.get(pk=request.POST['alkohol'])
    except (KeyError, Uzytkownik.DoesNotExist):
        return render(request, 'app/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        question_id += 1

    if question_id < 9:
        return HttpResponseRedirect(reverse('app:detail', args=(question.id+1,)))
    if request.POST['alkohol'] == "1":
        return HttpResponseRedirect(reverse('app:detail', args=(question.id+1,)))
    if request.POST['alkohol'] == "2":
        return HttpResponseRedirect(reverse('app:detail', args=(question.id+2,)))
    if request.POST['alkohol'] == "3":
        return HttpResponseRedirect(reverse('app:detail', args=(question.id+3,)))
    if request.POST['alkohol'] == "4":
        return HttpResponseRedirect(reverse('app:detail', args=(question.id+4,)))
    if request.POST['alkohol'] == "5":
        return render(request, "app/results.html")
    if question_id > 9:
        return render(request, "app/results.html")

app/templates/app/Wyniki.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Wyniki</title>
</head>

<body>
    <h1>Dziękujemy za udział w ankiecie. </h1>
    <p>Do zobaczenia następnym razem XDD</p>
</body>

</html>

app/templates/app/detail.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <title>Ankieta</title>
    </head>

    <body>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/ankieta.css' %}">

        <header><h1>{{ question.id }}/9 </h1></header>

        <ankieta>
            {% load static %}
            <h1> {{ question.question_text }}</h1>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            {% if question.question_text == "Ile masz lat?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                   <p>{% for uzytkownik in question.uzytkownik_set.all %}
                     <input type="radio" name="uzytkownik" id="uzytkownik{{ forloop.counter }}" value="{{ uzytkownik.id }}">
                         <label for="uzytkownik{{ forloop.counter }}">{{ uzytkownik.wiek }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Płeć:" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for uzytkownik in question.uzytkownik_set.all %}
                     <input type="radio" name="uzytkownik" id="uzytkownik{{ forloop.counter }}" value="{{ uzytkownik.id }}">
                        <label for="uzytkownik{{ forloop.counter }}">{{ uzytkownik.plec }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Ile mieszkańców ma twoje miasto?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for uzytkownik in question.uzytkownik_set.all %}
                     <input type="radio" name="uzytkownik" id="uzytkownik{{ forloop.counter }}" value="{{ uzytkownik.id }}">
                        <label for="uzytkownik{{ forloop.counter }}">{{ uzytkownik.miasto }}</label><br>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Jakie masz wykształcenie?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for uzytkownik in question.uzytkownik_set.all %}
                     <input type="radio" name="uzytkownik" id="uzytkownik{{ forloop.counter }}" value="{{ uzytkownik.id }}">
                        <label for="uzytkownik{{ forloop.counter }}">{{ uzytkownik.wyksztalcenie }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Co sprawia, że spożywasz alkohol?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for czestosc in question.czestosc_set.all %}
                     <input type="radio" name="czestosc" id="czestosc{{ forloop.counter }}" value="{{ czestosc.id }}">
                        <label for="czestosc{{ forloop.counter }}">{{ czestosc.okazja }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Jak często spożywasz alkohol?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for czestosc in question.czestosc_set.all %}
                     <input type="radio" name="czestosc" id="czestosc{{ forloop.counter }}" value="{{ czestosc.id }}">
                        <label for="czestosc{{ forloop.counter }}">{{ czestosc.czestotliwosc }}</label><br>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Kiedy pierwszy raz spożyłeś/aś alkohol?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for czestosc in question.czestosc_set.all %}
                     <input type="radio" name="czestosc" id="czestosc{{ forloop.counter }}" value="{{ czestosc.id }}">
                        <label for="czestosc{{ forloop.counter }}">{{ czestosc.pierwszy_kontakt }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Jaki rodzaj alkoholu najczęściej spożywasz?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for alkohol in question.alkohol_set.all %}
                     <input type="radio" name="alkohol" id="alkohol{{ forloop.counter }}" value="{{ alkohol.id }}">
                        <label for="alkohol{{ forloop.counter }}">{{ alkohol.rodzaj_alkoholu }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

             {% if question.question_text == "Ile piw wypiłeś/aś w ciągu ostatniego miesiąca?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for alkohol in question.alkohol_set.all %}
                     <input type="radio" name="alkohol" id="alkohol{{ forloop.counter }}" value="{{ alkohol.id }}">
                        <label for="alkohol{{ forloop.counter }}">{{ alkohol.piwo }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Ile wódki wypiłeś/aś w ciągu ostatniego miesiąca?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for alkohol in question.alkohol_set.all %}
                     <input type="radio" name="alkohol" id="alkohol{{ forloop.counter }}" value="{{ alkohol.id }}">
                        <label for="alkohol{{ forloop.counter }}">{{ alkohol.wodka }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Ile wina wypiłeś/aś w ciągu ostatniego miesiąca?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for alkohol in question.alkohol_set.all %}
                     <input type="radio" name="alkohol" id="alkohol{{ forloop.counter }}" value="{{ alkohol.id }}">
                        <label for="alkohol{{ forloop.counter }}">{{ alkohol.wino }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

            {% if question.question_text == "Ile innego alkoholu wypiłeś/aś w ciągu ostatniego miesiąca?" %}
                <form action="{% url 'app:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <p>{% for alkohol in question.alkohol_set.all %}
                     <input type="radio" name="alkohol" id="alkohol{{ forloop.counter }}" value="{{ alkohol.id }}">
                        <label for="alkohol{{ forloop.counter }}">{{ alkohol.inne }}</label>
                        {% endfor %}</p>
                    <p><br><input type="submit" value="Zaglosuj"></p>
                 </form>
            {% endif %}

        </ankieta>

        <footer>
            <p>Strona główna</p>
            <p>Statystyki</p>
        </footer>

    </body>

</html>

app/templates/app/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
       <li><a href="{% url 'app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<h1>LOL ERROR 404.</h1>
<p> Prima APRILIS</p>
<p>april fool XD</p>
{% endif %}

app/templates/app/results.html
Vote again?